language: node_js
node_js:
  - "4.4.0"
before_script:
  - npm install
  - gulp build
after_success:
  - eval "$(ssh-agent -s)" 
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy /srv/users/serverpilot/apps/sketchsheets/repo/sketchsheets.git
  - git push deploy
